version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: ap-northeast-2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      # Gradle Wrapper를 사용하므로 별도의 설치 불필요
      - echo "No additional software installation required due to Gradle Wrapper."
  pre_build:
    commands:
      - echo Build started on `date`
      - chmod +x gradlew
      - echo "Parameter Store에서 비밀값 가져오기"
      - DB_USER=$(aws ssm get-parameter --name "/yeoun/local/DB_USERNAME" --with-decryption --query "Parameter.Value" --output text)
      - DB_PASS=$(aws ssm get-parameter --name "/yeoun/local/DB_PASSWORD" --with-decryption --query "Parameter.Value" --output text)
      - |
        cat > src/main/resources/application.properties << EOF
        spring.application.name=Yeoun
        spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
        spring.datasource.url=jdbc:oracle:thin:@itwillbs.com:1601:ORCL2412
        spring.datasource.username=${DB_USER}
        spring.datasource.password=${DB_PASS}
        spring.jpa.hibernate.ddl-auto=update
        mybatis.mapper-locations=classpath:mapper/*.xml
        mybatis.configuration.map-underscore-to-camel-case= true
        logging.level.com.yeoun.approval.mapper=DEBUG
        # =========================================================================
        # [ 파일 업로드 설정 ]
        # 파일 한 개 당 최대 사이즈
        spring.servlet.multipart.max-file-size=10MB
        # 업로드 요청 한 건 당 전체 파일 최대 사이즈
        spring.servlet.multipart.max-request-size=50MB
        # 파일 업로드 경로
        # 1) 업로드 기본 경로
        file.uploadBaseLocation=/usr/local/tomcat/upload

        # [ 하이버네이트(JPA) 설정 ]
        # 애플리케이션 시작(또는 재시작) 시 테이블 자동 생성
        #spring.jpa.hibernate.ddl-auto=create
        # update 로 변경 시 애플리케이션 재시작 시에도 기존 테이블 그대로 유지됨.
        # 만약, 해당 테이블이 존재하지 않을 경우에는 최초 1회 테이블 생성도 수행함
        #spring.jpa.hibernate.ddl-auto=validate
        spring.jpa.hibernate.ddl-auto=update
        
        #data.sql 실행
        #spring.sql.init.mode=always
        spring.jpa.defer-datasource-initialization=true
        
        
        # =================================================
        # GET, POST 방식 외에 PUT, PATCH, DELETE 등의 요청 시 form 태그의 히든 파라미터로 "_method" 전송할 경우
        # 스프링에서 해당 파라미터를 요청 방식으로 인식하려면 히든 메서드 필터링 설정 추가
        spring.mvc.hiddenmethod.filter.enabled=true
        
        # =================================================
        # 마이바티스 설정
        # Mapper XML 파일 위치 설정
        mybatis.mapper-locations=classpath:mapper/*.xml
        mybatis.configuration.map-underscore-to-camel-case=true
        
        #=====================================================
        #잭슨 설정 
        spring.jackson.serialization.fail-on-empty-beans=false
        EOF
  build:
    commands:
      - echo Building the Spring Boot application
      - ./gradlew clean bootWar  # 빌드 명령
      - ls -l build/libs/
      - mv build/libs/myapp.war myapp.war
artifacts:
  files:
    - myapp.war
    - appspec.yml
    - scripts/*


